services:
  postgres:
    image: postgres:16
    container_name: postgres_memories
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      POSTGRES_DB: memories_diary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d memories_diary" ]
      interval: 5s
      timeout: 5s
      retries: 10

  memories-diary:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: memories_diary
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: