spring:
  application:
    name: memories-diary
  profiles:
    active: dev

---
# Desenvolvimento Local
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/memories_diary
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir}

file:
  upload-dir: uploads

api:
  security:
    token:
      secret: dev-secret
      expiration: 3600000

---
# Produção (Railway)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir}

server:
  port: ${PORT:8080}

file:
  upload-dir: uploads

api:
  security:
    token:
      secret: ${JWT_SECRET}
      expiration: 3600000